Update mymultipath

diff --git a/mymultipath b/mymultipath
--- a/mymultipath
+++ b/mymultipath
@@ -20,7 +20,7 @@ cp $0 /usr/local/bin
 fi
 
 
-
+ERR=0
 RED='\033[1;31m'
 GREEN='\033[1;32m'
 YELLOW='\033[1;33m'
@@ -29,17 +29,27 @@ NC='\033[0m' # No Color
 # SSY connection by RESTAPI
 #
 
-if [ -f /root/.SSY/credentials ] ; then
+if [ -f /etc/pve/storage.cfg ] ; then
 
   if [ $(whereis jq|wc -w) -le 1 ] ; then
     printf "${RED}JQ package is mandatory to gather data from SSY, please install the package using ${YELLOW}apt install jq${NC}\n"
     VDISKS=""
   else
-    SERVERHOST=$(awk -F"=" '/ServerHost/ {print $2}' /root/.SSY/credentials)
-    SSYUSER=$(awk -F"=" '/SSYUserName/ {print $2}' /root/.SSY/credentials)
-    SSYPWD=$(awk -F"=" '/SSYPassword/ {print $2}' /root/.SSY/credentials)
-    VDISKS=$(curl -s -m 3 -k -L -H "ServerHost: ${SERVERHOST}" -u${SSYUSER}:${SSYPWD} https://${SERVERHOST}/RestService/rest.svc/1.0/virtualdisks)
-    if [ $(echo $VDISKS|jq -e 'try(.ErrorsCode)') ]; then
+    PVECONF=$(cat /etc/pve/storage.cfg |grep -m1 -A5 datacore:)
+    SERVERHOST=$(printf "$PVECONF" |awk '/portals/ {print $2}'|sed "s/,/ /g")
+    SSYUSER=$(printf "$PVECONF" |awk '/DCusername/ {print $2}')
+    SSYPWD=$(printf "$PVECONF" |awk '/DCpassword/ {print $2}')
+    for DCHOST in $SERVERHOST
+      do
+        VDISKS=$(curl -s -m 1 -k -L -H "ServerHost: ${DCHOST}" -u${SSYUSER}:${SSYPWD} https://${DCHOST}/RestService/rest.svc/1.0/virtualdisks)
+        if [[ "$VDISKS" != "" ]] ; then
+           if ! [ $(echo $VDISKS|jq -e 'try(.ErrorsCode)') ]; then
+              ERR=1
+              break
+           fi
+        fi
+      done
+    if [ $(echo $ERR) -ne 1 ]; then
       VDISKS=""
       printf "${RED}Unable to gather data from SSY, please review the credential file${NC}\n"
     fi
@@ -47,6 +57,7 @@ if [ -f /root/.SSY/credentials ] ; then
 else
   VDISKS=""
 fi
+echo "DataCore node: $DCHOST"
 
 multipath -r
 sleep 2
